<script src="js/dwz/js/jquery-1.7.2.min.js" type="text/javascript"></script>
<script src="js/dwz/js/jquery.cookie.js" type="text/javascript"></script>
<script src="js/dwz/js/jquery.validate.js" type="text/javascript"></script>
<script src="js/dwz/js/jquery.bgiframe.js" type="text/javascript"></script>
<script src="js/dwz/js/speedup.js" type="text/javascript"></script>

<script src="js/dwz/js/dwz.core.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.util.date.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.validate.method.js" type="text/javascript"></script>

<script src="js/dwz/js/dwz.barDrag.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.drag.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.tree.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.accordion.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.ui.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.theme.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.switchEnv.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.alertMsg.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.contextmenu.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.navTab.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.tab.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.resize.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.dialog.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.dialogDrag.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.sortDrag.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.cssTable.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.stable.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.taskBar.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.ajax.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.pagination.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.database.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.datepicker.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.effects.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.panel.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.checkbox.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.history.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.combox.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.print.js" type="text/javascript"></script>
<script src="js/dwz/js/dwz.regional.zh.js" type="text/javascript"></script>